SELECT ACTOR.FULLNAME AS "Full Name", ACTOR.BIRTHDAY AS "Birthday", COUNT(ACTED.MOVIEID) AS "Number of Movies Acted" FROM ACTED
JOIN ACTOR ON ACTED.ACTORID = ACTOR.ACTORID
JOIN MOVIE ON ACTED.MOVIEID = MOVIE.MOVIEID
GROUP BY ACTOR.FULLNAME, ACTOR.BIRTHDAY
ORDER BY ACTOR.FULLNAME;