SELECT CUSTOMER.FULLNAME AS "Full Name", CUSTOMER.EMAIL AS "Email", MOVIE.MOVIENAME AS "Movie Name", MOVIE.GENRE AS "Genre", MOVIE.RUNTIME AS "Runtime", MOVIE.RELEASEDATE "Release Date" FROM CUSTOMER_OWNS
JOIN CUSTOMER ON CUSTOMER_OWNS.CUSTOMERID = CUSTOMER.CUSTOMERID
JOIN MOVIE ON CUSTOMER_OWNS.MOVIEID = MOVIE.MOVIEID
ORDER BY CUSTOMER.FULLNAME;