SELECT PURCHASE.PURCHASEID AS "Purchase ID", PURCHASE.PURCHASEDATE AS "Purchase Date", MOVIE.MOVIENAME AS "Movie Name", MOVIE.GENRE AS "Genre", MOVIE.RUNTIME AS "Runtime", MOVIE.RELEASEDATE AS "Release Date" FROM MOVIE_PURCHASED
JOIN PURCHASE ON MOVIE_PURCHASED.PURCHASEID = PURCHASE.PURCHASEID
JOIN MOVIE ON MOVIE_PURCHASED.MOVIEID = MOVIE.MOVIEID
ORDER BY PURCHASE.PURCHASEDATE;