SELECT CustomerID FROM PURCHASE
WHERE EXISTS (SELECT 2 FROM MOVIE_PURCHASED 
    JOIN ACTED ON MOVIE_PURCHASED.MovieID = ACTED.MovieID 
    WHERE PURCHASE.PurchaseID = MOVIE_PURCHASED.PurchaseID)
UNION
SELECT CustomerID FROM CUSTOMER_OWNS
    WHERE EXISTS (SELECT 2 FROM ACTED WHERE CUSTOMER_OWNS.MovieID = ACTED.MovieID);
